# Process APT experiment

## Label the dataset
For each experiment, there is a dedicated folder containing:
- .csv converted from .pcap file, containing extracted flows.
- .pkl contains time intervals in which attacks are performed (and additional info)
- .npz contains datetime objects that mark the start of the experiment.

In [1]:
import pandas as pd
import numpy as np
from datetime import datetime
import pytz
import pickle

In [2]:
root = "./data/dollar_char_train/"
csv_file = root + "dollar_char_train.csv"
intervals = root + "dollar_char_train.pkl"
start = root + "dollar_char_train.npz"

### Load experiment timestamps
We load the timestamps indicating the start and the end of each attacker phase/step.

In [3]:
import pickle
with open(intervals, 'rb') as f:
    loaded_data = pickle.load(f)

In [4]:
len(loaded_data)

533

In [5]:
loaded_data

[{'phase_number': 1,
  'step_number': 1,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'RECONNAISSANCE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 11, 16, 388096, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 11, 16, 576507, tzinfo=<UTC>),
  'command': 'netstat',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 2,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 11, 16, 576560, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 12, 23, 815582, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 1,
  'step_number': 3,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'RECONNAISSANCE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 12, 23, 815666, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 12, 23, 888013, tzinfo=<UTC>),
  'command': 'nmap_192_T4',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 4,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 12, 23, 888061, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 13, 56, 712519, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 1,
  'step_number': 5,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'RECONNAISSANCE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 13, 56, 712583, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 14, 52, 953673, tzinfo=<UTC>),
  'command': 'nmap_10_T5',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 6,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 14, 52, 953724, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 16, 10, 76403, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 1,
  'step_number': 7,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'RECONNAISSANCE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 16, 10, 76469, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 16, 10, 259575, tzinfo=<UTC>),
  'command': 'netstat',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 8,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 16, 10, 259655, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 16, 58, 812552, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 1,
  'step_number': 9,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'RECONNAISSANCE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 16, 58, 812600, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 16, 58, 891779, tzinfo=<UTC>),
  'command': 'nmap_192_T4',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 10,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 16, 58, 891823, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 17, 51, 334747, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 1,
  'step_number': 11,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'RECONNAISSANCE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 17, 51, 334813, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 18, 48, 138180, tzinfo=<UTC>),
  'command': 'nmap_10_T5',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 12,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 18, 48, 138228, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 20, 5, 46176, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 1,
  'step_number': 13,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'RECONNAISSANCE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 20, 5, 46240, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 20, 5, 247713, tzinfo=<UTC>),
  'command': 'netstat',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 14,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 20, 5, 247769, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 21, 44, 823520, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 1,
  'step_number': 15,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'RECONNAISSANCE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 21, 44, 823583, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 21, 44, 901148, tzinfo=<UTC>),
  'command': 'nmap_192_T4',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 16,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 21, 44, 901193, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 23, 22, 618240, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 1,
  'step_number': 17,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'RECONNAISSANCE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 23, 22, 618306, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 24, 18, 820260, tzinfo=<UTC>),
  'command': 'nmap_10_T5',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 18,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 24, 18, 820309, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 25, 15, 932444, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 1,
  'step_number': 19,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'RECONNAISSANCE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 25, 15, 932510, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 25, 16, 114213, tzinfo=<UTC>),
  'command': 'netstat',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 20,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 25, 16, 114262, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 26, 25, 440003, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 1,
  'step_number': 21,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'RECONNAISSANCE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 26, 25, 440061, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 26, 25, 518595, tzinfo=<UTC>),
  'command': 'nmap_192_T4',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 22,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 26, 25, 518638, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 27, 11, 560460, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 1,
  'step_number': 23,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'RECONNAISSANCE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 27, 11, 560526, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 28, 7, 402435, tzinfo=<UTC>),
  'command': 'nmap_10_T5',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 24,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 28, 7, 402499, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 29, 17, 974514, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 1,
  'step_number': 25,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'RECONNAISSANCE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 29, 17, 974578, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 29, 18, 151602, tzinfo=<UTC>),
  'command': 'netstat',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 26,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 29, 18, 151639, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 30, 23, 484735, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 1,
  'step_number': 27,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'RECONNAISSANCE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 30, 23, 484804, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 30, 23, 565805, tzinfo=<UTC>),
  'command': 'nmap_192_T4',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 28,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 30, 23, 565841, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 31, 31, 276317, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 1,
  'step_number': 29,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'RECONNAISSANCE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 31, 31, 276369, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 32, 27, 481711, tzinfo=<UTC>),
  'command': 'nmap_10_T5',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 30,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 32, 27, 481759, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 33, 26, 738090, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 1,
  'step_number': 31,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'RECONNAISSANCE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 33, 26, 738142, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 33, 26, 926333, tzinfo=<UTC>),
  'command': 'netstat',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 32,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 33, 26, 926382, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 35, 4, 888441, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 1,
  'step_number': 33,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'RECONNAISSANCE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 35, 4, 888508, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 35, 4, 978846, tzinfo=<UTC>),
  'command': 'nmap_192_T4',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 34,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 35, 4, 978896, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 36, 43, 71190, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 1,
  'step_number': 35,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'RECONNAISSANCE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 36, 43, 71279, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 37, 39, 350205, tzinfo=<UTC>),
  'command': 'nmap_10_T5',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 36,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 37, 39, 350255, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 38, 36, 138420, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 2,
  'step_number': 37,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'BRUTE_FORCE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 38, 36, 138488, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 53, 30, 140402, tzinfo=<UTC>),
  'command': 'brute_force_malformed',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 38,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 53, 30, 140435, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 54, 30, 916234, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 4,
  'step_number': 39,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'DISCOVERY',
  'start_time': datetime.datetime(2025, 8, 19, 19, 54, 30, 916328, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 55, 26, 182155, tzinfo=<UTC>),
  'command': 'nmap_sub',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 40,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 55, 26, 182230, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 56, 53, 315706, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 4,
  'step_number': 41,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'DISCOVERY',
  'start_time': datetime.datetime(2025, 8, 19, 19, 56, 53, 315772, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 56, 59, 498702, tzinfo=<UTC>),
  'command': 'mqtt_cat',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 42,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 56, 59, 498740, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 58, 23, 45589, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 4,
  'step_number': 43,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'DISCOVERY',
  'start_time': datetime.datetime(2025, 8, 19, 19, 58, 23, 45684, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 59, 18, 260577, tzinfo=<UTC>),
  'command': 'nmap_sub',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 44,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 59, 18, 260614, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 20, 0, 45, 328256, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 4,
  'step_number': 45,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'DISCOVERY',
  'start_time': datetime.datetime(2025, 8, 19, 20, 0, 45, 328311, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 20, 0, 51, 503461, tzinfo=<UTC>),
  'command': 'mqtt_cat',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 46,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 20, 0, 51, 503508, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 20, 1, 26, 473294, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 4,
  'step_number': 47,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'DISCOVERY',
  'start_time': datetime.datetime(2025, 8, 19, 20, 1, 26, 473361, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 20, 2, 21, 690987, tzinfo=<UTC>),
  'command': 'nmap_sub',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 48,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 20, 2, 21, 691025, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 20, 3, 30, 139711, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 4,
  'step_number': 49,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'DISCOVERY',
  'start_time': datetime.datetime(2025, 8, 19, 20, 3, 30, 139777, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 20, 3, 36, 318052, tzinfo=<UTC>),
  'command': 'mqtt_cat',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 50,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 20, 3, 36, 318099, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 20, 5, 6, 71089, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 4,
  'step_number': 51,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'DISCOVERY',
  'start_time': datetime.datetime(2025, 8, 19, 20, 5, 6, 71140, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 20, 6, 1, 291868, tzinfo=<UTC>),
  'command': 'nmap_sub',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 52,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 20, 6, 1, 291912, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 20, 7, 29, 890632, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 4,
  'step_number': 53,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'DISCOVERY',
  'start_time': datetime.datetime(2025, 8, 19, 20, 7, 29, 890686, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 20, 7, 36, 64529, tzinfo=<UTC>),
  'command': 'mqtt_cat',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 54,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 20, 7, 36, 64575, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 20, 8, 49, 661039, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 4,
  'step_number': 55,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'DISCOVERY',
  'start_time': datetime.datetime(2025, 8, 19, 20, 8, 49, 661093, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 20, 9, 44, 876093, tzinfo=<UTC>),
  'command': 'nmap_sub',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 56,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 20, 9, 44, 876138, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 20, 10, 35, 954834, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 4,
  'step_number': 57,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'DISCOVERY',
  'start_time': datetime.datetime(2025, 8, 19, 20, 10, 35, 954895, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 20, 10, 42, 126947, tzinfo=<UTC>),
  'command': 'mqtt_cat',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 58,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 20, 10, 42, 127022, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 20, 11, 24, 707923, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 4,
  'step_number': 59,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'DISCOVERY',
  'start_time': datetime.datetime(2025, 8, 19, 20, 11, 24, 708004, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 20, 12, 19, 928686, tzinfo=<UTC>),
  'command': 'nmap_sub',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 60,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 20, 12, 19, 928732, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 20, 13, 47, 839528, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 4,
  'step_number': 61,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'DISCOVERY',

### Load CSV network traffic

In [6]:
df = pd.read_csv(csv_file)

/tmp/ipykernel_2294720/298181477.py:1: DtypeWarning: Columns (0: requested_server_name, 1: client_fingerprint, 2: server_fingerprint) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv_file)

In [7]:
df.shape

(198928, 87)

In [8]:
list(df.columns)

['Unnamed: 0',
 'id',
 'expiration_id',
 'src_ip',
 'src_mac',
 'src_oui',
 'src_port',
 'dst_ip',
 'dst_mac',
 'dst_oui',
 'dst_port',
 'protocol',
 'ip_version',
 'vlan_id',
 'tunnel_id',
 'bidirectional_first_seen_ms',
 'bidirectional_last_seen_ms',
 'bidirectional_duration_ms',
 'bidirectional_packets',
 'bidirectional_bytes',
 'src2dst_first_seen_ms',
 'src2dst_last_seen_ms',
 'src2dst_duration_ms',
 'src2dst_packets',
 'src2dst_bytes',
 'dst2src_first_seen_ms',
 'dst2src_last_seen_ms',
 'dst2src_duration_ms',
 'dst2src_packets',
 'dst2src_bytes',
 'bidirectional_min_ps',
 'bidirectional_mean_ps',
 'bidirectional_stddev_ps',
 'bidirectional_max_ps',
 'src2dst_min_ps',
 'src2dst_mean_ps',
 'src2dst_stddev_ps',
 'src2dst_max_ps',
 'dst2src_min_ps',
 'dst2src_mean_ps',
 'dst2src_stddev_ps',
 'dst2src_max_ps',
 'bidirectional_min_piat_ms',
 'bidirectional_mean_piat_ms',
 'bidirectional_stddev_piat_ms',
 'bidirectional_max_piat_ms',
 'src2dst_min_piat_ms',
 'src2dst_mean_piat_ms',
 'src2dst_stddev_piat_ms',
 'src2dst_max_piat_ms',
 'dst2src_min_piat_ms',
 'dst2src_mean_piat_ms',
 'dst2src_stddev_piat_ms',
 'dst2src_max_piat_ms',
 'bidirectional_syn_packets',
 'bidirectional_cwr_packets',
 'bidirectional_ece_packets',
 'bidirectional_urg_packets',
 'bidirectional_ack_packets',
 'bidirectional_psh_packets',
 'bidirectional_rst_packets',
 'bidirectional_fin_packets',
 'src2dst_syn_packets',
 'src2dst_cwr_packets',
 'src2dst_ece_packets',
 'src2dst_urg_packets',
 'src2dst_ack_packets',
 'src2dst_psh_packets',
 'src2dst_rst_packets',
 'src2dst_fin_packets',
 'dst2src_syn_packets',
 'dst2src_cwr_packets',
 'dst2src_ece_packets',
 'dst2src_urg_packets',
 'dst2src_ack_packets',
 'dst2src_psh_packets',
 'dst2src_rst_packets',
 'dst2src_fin_packets',
 'application_name',
 'application_category_name',
 'application_is_guessed',
 'application_confidence',
 'requested_server_name',
 'client_fingerprint',
 'server_fingerprint',
 'user_agent',
 'content_type']

In [9]:
df['bidirectional_first_seen_ms']

0               10
1              348
2              412
3              460
4              476
            ...
198923    35975349
198924    35980391
198925    35984433
198926    35989473
198927    35997511
Name: bidirectional_first_seen_ms, Length: 198928, dtype: int64

### Load experiment timestamps
We load the timestamps indicating the start and the end of each attacker phase/step.

In [10]:
import pickle
with open(intervals, 'rb') as f:
    loaded_data = pickle.load(f)

In [11]:
len(loaded_data)

533

In [12]:
loaded_data

[{'phase_number': 1,
  'step_number': 1,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'RECONNAISSANCE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 11, 16, 388096, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 11, 16, 576507, tzinfo=<UTC>),
  'command': 'netstat',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 2,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 11, 16, 576560, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 12, 23, 815582, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 1,
  'step_number': 3,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'RECONNAISSANCE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 12, 23, 815666, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 12, 23, 888013, tzinfo=<UTC>),
  'command': 'nmap_192_T4',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 4,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 12, 23, 888061, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 13, 56, 712519, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 1,
  'step_number': 5,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'RECONNAISSANCE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 13, 56, 712583, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 14, 52, 953673, tzinfo=<UTC>),
  'command': 'nmap_10_T5',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 6,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 14, 52, 953724, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 16, 10, 76403, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 1,
  'step_number': 7,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'RECONNAISSANCE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 16, 10, 76469, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 16, 10, 259575, tzinfo=<UTC>),
  'command': 'netstat',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 8,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 16, 10, 259655, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 16, 58, 812552, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 1,
  'step_number': 9,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'RECONNAISSANCE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 16, 58, 812600, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 16, 58, 891779, tzinfo=<UTC>),
  'command': 'nmap_192_T4',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 10,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 16, 58, 891823, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 17, 51, 334747, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 1,
  'step_number': 11,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'RECONNAISSANCE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 17, 51, 334813, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 18, 48, 138180, tzinfo=<UTC>),
  'command': 'nmap_10_T5',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 12,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 18, 48, 138228, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 20, 5, 46176, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 1,
  'step_number': 13,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'RECONNAISSANCE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 20, 5, 46240, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 20, 5, 247713, tzinfo=<UTC>),
  'command': 'netstat',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 14,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 20, 5, 247769, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 21, 44, 823520, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 1,
  'step_number': 15,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'RECONNAISSANCE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 21, 44, 823583, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 21, 44, 901148, tzinfo=<UTC>),
  'command': 'nmap_192_T4',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 16,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 21, 44, 901193, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 23, 22, 618240, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 1,
  'step_number': 17,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'RECONNAISSANCE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 23, 22, 618306, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 24, 18, 820260, tzinfo=<UTC>),
  'command': 'nmap_10_T5',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 18,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 24, 18, 820309, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 25, 15, 932444, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 1,
  'step_number': 19,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'RECONNAISSANCE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 25, 15, 932510, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 25, 16, 114213, tzinfo=<UTC>),
  'command': 'netstat',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 20,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 25, 16, 114262, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 26, 25, 440003, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 1,
  'step_number': 21,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'RECONNAISSANCE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 26, 25, 440061, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 26, 25, 518595, tzinfo=<UTC>),
  'command': 'nmap_192_T4',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 22,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 26, 25, 518638, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 27, 11, 560460, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 1,
  'step_number': 23,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'RECONNAISSANCE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 27, 11, 560526, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 28, 7, 402435, tzinfo=<UTC>),
  'command': 'nmap_10_T5',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 24,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 28, 7, 402499, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 29, 17, 974514, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 1,
  'step_number': 25,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'RECONNAISSANCE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 29, 17, 974578, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 29, 18, 151602, tzinfo=<UTC>),
  'command': 'netstat',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 26,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 29, 18, 151639, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 30, 23, 484735, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 1,
  'step_number': 27,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'RECONNAISSANCE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 30, 23, 484804, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 30, 23, 565805, tzinfo=<UTC>),
  'command': 'nmap_192_T4',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 28,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 30, 23, 565841, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 31, 31, 276317, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 1,
  'step_number': 29,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'RECONNAISSANCE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 31, 31, 276369, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 32, 27, 481711, tzinfo=<UTC>),
  'command': 'nmap_10_T5',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 30,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 32, 27, 481759, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 33, 26, 738090, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 1,
  'step_number': 31,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'RECONNAISSANCE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 33, 26, 738142, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 33, 26, 926333, tzinfo=<UTC>),
  'command': 'netstat',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 32,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 33, 26, 926382, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 35, 4, 888441, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 1,
  'step_number': 33,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'RECONNAISSANCE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 35, 4, 888508, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 35, 4, 978846, tzinfo=<UTC>),
  'command': 'nmap_192_T4',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 34,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 35, 4, 978896, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 36, 43, 71190, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 1,
  'step_number': 35,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'RECONNAISSANCE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 36, 43, 71279, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 37, 39, 350205, tzinfo=<UTC>),
  'command': 'nmap_10_T5',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 36,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 37, 39, 350255, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 38, 36, 138420, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 2,
  'step_number': 37,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'BRUTE_FORCE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 38, 36, 138488, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 53, 30, 140402, tzinfo=<UTC>),
  'command': 'brute_force_malformed',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 38,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 53, 30, 140435, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 54, 30, 916234, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 4,
  'step_number': 39,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'DISCOVERY',
  'start_time': datetime.datetime(2025, 8, 19, 19, 54, 30, 916328, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 55, 26, 182155, tzinfo=<UTC>),
  'command': 'nmap_sub',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 40,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 55, 26, 182230, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 56, 53, 315706, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 4,
  'step_number': 41,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'DISCOVERY',
  'start_time': datetime.datetime(2025, 8, 19, 19, 56, 53, 315772, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 56, 59, 498702, tzinfo=<UTC>),
  'command': 'mqtt_cat',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 42,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 56, 59, 498740, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 58, 23, 45589, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 4,
  'step_number': 43,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'DISCOVERY',
  'start_time': datetime.datetime(2025, 8, 19, 19, 58, 23, 45684, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 19, 59, 18, 260577, tzinfo=<UTC>),
  'command': 'nmap_sub',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 44,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 19, 59, 18, 260614, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 20, 0, 45, 328256, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 4,
  'step_number': 45,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'DISCOVERY',
  'start_time': datetime.datetime(2025, 8, 19, 20, 0, 45, 328311, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 20, 0, 51, 503461, tzinfo=<UTC>),
  'command': 'mqtt_cat',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 46,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 20, 0, 51, 503508, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 20, 1, 26, 473294, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 4,
  'step_number': 47,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'DISCOVERY',
  'start_time': datetime.datetime(2025, 8, 19, 20, 1, 26, 473361, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 20, 2, 21, 690987, tzinfo=<UTC>),
  'command': 'nmap_sub',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 48,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 20, 2, 21, 691025, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 20, 3, 30, 139711, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 4,
  'step_number': 49,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'DISCOVERY',
  'start_time': datetime.datetime(2025, 8, 19, 20, 3, 30, 139777, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 20, 3, 36, 318052, tzinfo=<UTC>),
  'command': 'mqtt_cat',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 50,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 20, 3, 36, 318099, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 20, 5, 6, 71089, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 4,
  'step_number': 51,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'DISCOVERY',
  'start_time': datetime.datetime(2025, 8, 19, 20, 5, 6, 71140, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 20, 6, 1, 291868, tzinfo=<UTC>),
  'command': 'nmap_sub',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 52,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 20, 6, 1, 291912, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 20, 7, 29, 890632, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 4,
  'step_number': 53,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'DISCOVERY',
  'start_time': datetime.datetime(2025, 8, 19, 20, 7, 29, 890686, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 20, 7, 36, 64529, tzinfo=<UTC>),
  'command': 'mqtt_cat',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 54,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 20, 7, 36, 64575, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 20, 8, 49, 661039, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 4,
  'step_number': 55,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'DISCOVERY',
  'start_time': datetime.datetime(2025, 8, 19, 20, 8, 49, 661093, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 20, 9, 44, 876093, tzinfo=<UTC>),
  'command': 'nmap_sub',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 56,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 20, 9, 44, 876138, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 20, 10, 35, 954834, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 4,
  'step_number': 57,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'DISCOVERY',
  'start_time': datetime.datetime(2025, 8, 19, 20, 10, 35, 954895, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 20, 10, 42, 126947, tzinfo=<UTC>),
  'command': 'mqtt_cat',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 58,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 20, 10, 42, 127022, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 20, 11, 24, 707923, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 4,
  'step_number': 59,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'DISCOVERY',
  'start_time': datetime.datetime(2025, 8, 19, 20, 11, 24, 708004, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 20, 12, 19, 928686, tzinfo=<UTC>),
  'command': 'nmap_sub',
  'iteration': 0},
 {'phase_number': -1,
  'step_number': 60,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'PAUSE',
  'start_time': datetime.datetime(2025, 8, 19, 20, 12, 19, 928732, tzinfo=<UTC>),
  'end_time': datetime.datetime(2025, 8, 19, 20, 13, 47, 839528, tzinfo=<UTC>),
  'command': 'pause',
  'iteration': 0},
 {'phase_number': 4,
  'step_number': 61,
  'attack_name': 'dollar_char_dos_scp_inst_cam_train',
  'phase_name': 'DISCOVERY',

### Count sequences for attack type

In [13]:
from collections import Counter
command_counts = Counter(item['command'] for item in loaded_data)
print(command_counts)

Counter({'pause': 284, 'dollar_char': 166, 'nmap_mqtt': 21, 'nmap_banner': 14, 'netstat': 9, 'nmap_10_T5': 9, 'nmap_192_T4': 8, 'nmap_sub': 7, 'mqtt_cat': 7, 'scp_inst': 7, 'brute_force_malformed': 1})

Load start_time FROM .npy file. This is the starting timestamp of the apt simulation.

### Uniform time zone for start timestamp and experiment timestamps

In [14]:
start_time = np.load(start, allow_pickle=True)
start_time = start_time['datetime']

In [15]:
start_time

array(datetime.datetime(2025, 8, 19, 21, 6, 57, 247039), dtype=object)

In [16]:
start_time = start_time.item().replace(hour=start_time.item().hour -2)

In [17]:
start_time

datetime.datetime(2025, 8, 19, 19, 6, 57, 247039)

### Convert relative timestamps to UTC

We convert the 'layers.frame.frame.time_epoch' relative time to absolute UTC timestamps using as reference the start_time we load from the .npy file.

In [18]:
from datetime import datetime, timedelta
def convert_to_absolute_time(epoch_seconds, start_time):
    utc=pytz.UTC
    relative_time = timedelta(milliseconds=epoch_seconds)
    absolute_time = start_time + relative_time
    absolute_time = utc.localize(absolute_time)
    return absolute_time

df['timestamp'] = df['bidirectional_first_seen_ms'].apply(convert_to_absolute_time, start_time=start_time)

In [19]:
df['timestamp'], df['bidirectional_first_seen_ms']

(0        2025-08-19 19:06:57.257039+00:00
 1        2025-08-19 19:06:57.595039+00:00
 2        2025-08-19 19:06:57.659039+00:00
 3        2025-08-19 19:06:57.707039+00:00
 4        2025-08-19 19:06:57.723039+00:00
                        ...
 198923   2025-08-20 05:06:32.596039+00:00
 198924   2025-08-20 05:06:37.638039+00:00
 198925   2025-08-20 05:06:41.680039+00:00
 198926   2025-08-20 05:06:46.720039+00:00
 198927   2025-08-20 05:06:54.758039+00:00
 Name: timestamp, Length: 198928, dtype: datetime64[us, UTC],
 0               10
 1              348
 2              412
 3              460
 4              476
             ...
 198923    35975349
 198924    35980391
 198925    35984433
 198926    35989473
 198927    35997511
 Name: bidirectional_first_seen_ms, Length: 198928, dtype: int64)

### Assign labels
- We assign labels based on phase name:  if observation is in the start_time and end_time of a phase is marked with the corresponding phase name.
- Not labeled observations are marked as "discard": they correspond sleep times between attacker steps/technique.

In [20]:
import numpy as np
import pandas as pd

ph = pd.DataFrame(loaded_data)

print(ph)

     phase_number  step_number                         attack_name  \
0               1            1  dollar_char_dos_scp_inst_cam_train
1              -1            2  dollar_char_dos_scp_inst_cam_train
2               1            3  dollar_char_dos_scp_inst_cam_train
3              -1            4  dollar_char_dos_scp_inst_cam_train
4               1            5  dollar_char_dos_scp_inst_cam_train
..            ...          ...                                 ...
528            -1          529  dollar_char_dos_scp_inst_cam_train
529             5          530  dollar_char_dos_scp_inst_cam_train
530            -1          531  dollar_char_dos_scp_inst_cam_train
531            -1          532  dollar_char_dos_scp_inst_cam_train
532            -1          533  dollar_char_dos_scp_inst_cam_train

         phase_name                       start_time  \
0    RECONNAISSANCE 2025-08-19 19:11:16.388096+00:00
1             PAUSE 2025-08-19 19:11:16.576560+00:00
2    RECONNAISSANCE 2025-08-19 19:12:23.815666+00:00
3             PAUSE 2025-08-19 19:12:23.888061+00:00
4    RECONNAISSANCE 2025-08-19 19:13:56.712583+00:00
..              ...                              ...
528           PAUSE 2025-08-20 05:04:22.441247+00:00
529         EXPLOIT 2025-08-20 05:05:21.971090+00:00
530           PAUSE 2025-08-20 05:06:11.188650+00:00
531           PAUSE 2025-08-20 05:07:13.008173+00:00
532           PAUSE 2025-08-20 05:08:15.308582+00:00

                            end_time      command  iteration
0   2025-08-19 19:11:16.576507+00:00      netstat          0
1   2025-08-19 19:12:23.815582+00:00        pause          0
2   2025-08-19 19:12:23.888013+00:00  nmap_192_T4          0
3   2025-08-19 19:13:56.712519+00:00        pause          0
4   2025-08-19 19:14:52.953673+00:00   nmap_10_T5          0
..                               ...          ...        ...
528 2025-08-20 05:05:21.971022+00:00        pause          0
529 2025-08-20 05:06:11.188566+00:00  dollar_char          0
530 2025-08-20 05:07:13.008094+00:00        pause          0
531 2025-08-20 05:08:15.308518+00:00        pause          0
532 2025-08-20 05:08:51.144423+00:00        pause          0

[533 rows x 8 columns]

In [21]:
ph[0:10]

,phase_number,step_number,attack_name,phase_name,start_time,end_time,command,iteration
0,1,1,dollar_char_dos_scp_inst_cam_train,RECONNAISSANCE,2025-08-19 19:11:16.388096+00:00,2025-08-19 19:11:16.576507+00:00,netstat,0
1,-1,2,dollar_char_dos_scp_inst_cam_train,PAUSE,2025-08-19 19:11:16.576560+00:00,2025-08-19 19:12:23.815582+00:00,pause,0
2,1,3,dollar_char_dos_scp_inst_cam_train,RECONNAISSANCE,2025-08-19 19:12:23.815666+00:00,2025-08-19 19:12:23.888013+00:00,nmap_192_T4,0
3,-1,4,dollar_char_dos_scp_inst_cam_train,PAUSE,2025-08-19 19:12:23.888061+00:00,2025-08-19 19:13:56.712519+00:00,pause,0
4,1,5,dollar_char_dos_scp_inst_cam_train,RECONNAISSANCE,2025-08-19 19:13:56.712583+00:00,2025-08-19 19:14:52.953673+00:00,nmap_10_T5,0
5,-1,6,dollar_char_dos_scp_inst_cam_train,PAUSE,2025-08-19 19:14:52.953724+00:00,2025-08-19 19:16:10.076403+00:00,pause,0
6,1,7,dollar_char_dos_scp_inst_cam_train,RECONNAISSANCE,2025-08-19 19:16:10.076469+00:00,2025-08-19 19:16:10.259575+00:00,netstat,0
7,-1,8,dollar_char_dos_scp_inst_cam_train,PAUSE,2025-08-19 19:16:10.259655+00:00,2025-08-19 19:16:58.812552+00:00,pause,0
8,1,9,dollar_char_dos_scp_inst_cam_train,RECONNAISSANCE,2025-08-19 19:16:58.812600+00:00,2025-08-19 19:16:58.891779+00:00,nmap_192_T4,0
9,-1,10,dollar_char_dos_scp_inst_cam_train,PAUSE,2025-08-19 19:16:58.891823+00:00,2025-08-19 19:17:51.334747+00:00,pause,0

In [22]:
ph['start_time'] = pd.to_datetime(ph['start_time'], utc=True)
ph['end_time']   = pd.to_datetime(ph['end_time'],   utc=True)
df['timestamp']  = pd.to_datetime(df['timestamp'],  utc=True)

In [23]:
df['timestamp']

0        2025-08-19 19:06:57.257039+00:00
1        2025-08-19 19:06:57.595039+00:00
2        2025-08-19 19:06:57.659039+00:00
3        2025-08-19 19:06:57.707039+00:00
4        2025-08-19 19:06:57.723039+00:00
                       ...
198923   2025-08-20 05:06:32.596039+00:00
198924   2025-08-20 05:06:37.638039+00:00
198925   2025-08-20 05:06:41.680039+00:00
198926   2025-08-20 05:06:46.720039+00:00
198927   2025-08-20 05:06:54.758039+00:00
Name: timestamp, Length: 198928, dtype: datetime64[us, UTC]

In [24]:
ph['end_time']

0     2025-08-19 19:11:16.576507+00:00
1     2025-08-19 19:12:23.815582+00:00
2     2025-08-19 19:12:23.888013+00:00
3     2025-08-19 19:13:56.712519+00:00
4     2025-08-19 19:14:52.953673+00:00
                    ...
528   2025-08-20 05:05:21.971022+00:00
529   2025-08-20 05:06:11.188566+00:00
530   2025-08-20 05:07:13.008094+00:00
531   2025-08-20 05:08:15.308518+00:00
532   2025-08-20 05:08:51.144423+00:00
Name: end_time, Length: 533, dtype: datetime64[us, UTC]

In [25]:
ph['start_time']

0     2025-08-19 19:11:16.388096+00:00
1     2025-08-19 19:11:16.576560+00:00
2     2025-08-19 19:12:23.815666+00:00
3     2025-08-19 19:12:23.888061+00:00
4     2025-08-19 19:13:56.712583+00:00
                    ...
528   2025-08-20 05:04:22.441247+00:00
529   2025-08-20 05:05:21.971090+00:00
530   2025-08-20 05:06:11.188650+00:00
531   2025-08-20 05:07:13.008173+00:00
532   2025-08-20 05:08:15.308582+00:00
Name: start_time, Length: 533, dtype: datetime64[us, UTC]

In [26]:
iv = pd.IntervalIndex.from_arrays(ph['start_time'], ph['end_time'], closed='both')

In [27]:
iv

IntervalIndex([[2025-08-19 19:11:16.388096+00:00, 2025-08-19 19:11:16.576507+00:00],
               [2025-08-19 19:11:16.576560+00:00, 2025-08-19 19:12:23.815582+00:00],
               [2025-08-19 19:12:23.815666+00:00, 2025-08-19 19:12:23.888013+00:00],
               [2025-08-19 19:12:23.888061+00:00, 2025-08-19 19:13:56.712519+00:00],
               [2025-08-19 19:13:56.712583+00:00, 2025-08-19 19:14:52.953673+00:00],
               [2025-08-19 19:14:52.953724+00:00, 2025-08-19 19:16:10.076403+00:00],
               [2025-08-19 19:16:10.076469+00:00, 2025-08-19 19:16:10.259575+00:00],
               [2025-08-19 19:16:10.259655+00:00, 2025-08-19 19:16:58.812552+00:00],
               [2025-08-19 19:16:58.812600+00:00, 2025-08-19 19:16:58.891779+00:00],
               [2025-08-19 19:16:58.891823+00:00, 2025-08-19 19:17:51.334747+00:00],
               ...
               [2025-08-20 05:00:12.399613+00:00, 2025-08-20 05:00:51.596943+00:00],
               [2025-08-20 05:00:51.597028+00:00, 2025-08-20 05:02:18.900151+00:00],
               [2025-08-20 05:02:18.900217+00:00, 2025-08-20 05:02:58.146209+00:00],
               [2025-08-20 05:02:58.146270+00:00, 2025-08-20 05:03:32.220500+00:00],
               [2025-08-20 05:03:32.220582+00:00, 2025-08-20 05:04:22.441171+00:00],
               [2025-08-20 05:04:22.441247+00:00, 2025-08-20 05:05:21.971022+00:00],
               [2025-08-20 05:05:21.971090+00:00, 2025-08-20 05:06:11.188566+00:00],
               [2025-08-20 05:06:11.188650+00:00, 2025-08-20 05:07:13.008094+00:00],
               [2025-08-20 05:07:13.008173+00:00, 2025-08-20 05:08:15.308518+00:00],
               [2025-08-20 05:08:15.308582+00:00, 2025-08-20 05:08:51.144423+00:00]],
              dtype='interval[datetime64[us, UTC], both]', length=533)

In [28]:
idx = iv.get_indexer(df['timestamp'])

In [29]:
idx

array([ -1,  -1,  -1, ..., 530, 530, 530], shape=(198928,))

In [30]:
df['phase_idx']     = idx
df['phase_name']    = np.where(idx >= 0, ph['phase_name'].to_numpy()[idx], None)
df['label']         = np.where(idx >= 0, ph['command'].to_numpy()[idx], 'discard')
df['phase_number']  = np.where(idx >= 0, ph['phase_number'].to_numpy()[idx], None)
df['step_number']   = np.where(idx >= 0, ph['step_number'].to_numpy()[idx], None)

In [31]:
df['label'].value_counts()

label
nmap_10_T5               189139
pause                      3667
dollar_char                1995
nmap_mqtt                  1797
nmap_banner                1070
brute_force_malformed       659
nmap_sub                    368
discard                     217
mqtt_cat                      9
scp_inst                      7
Name: count, dtype: int64

In [32]:
df['phase_name'].value_counts()

phase_name
RECONNAISSANCE    189139
PAUSE               3667
DISCOVERY           3244
EXPLOIT             1995
BRUTE_FORCE          659
INSTALLATION           7
Name: count, dtype: int64

In [33]:
print(f"step number - {len(df['step_number'].value_counts().keys())}")
print("step_number")
for name, value in df['step_number'].value_counts().items():
    print(f"{name}:\t{value}")

step number - 513
step_number
17:	21050
5:	21017
35:	21014
11:	21010
23:	21010
219:	21010
231:	21010
29:	21009
225:	21009
37:	659
421:	160
450:	95
277:	88
69:	87
121:	87
333:	87
478:	87
77:	86
81:	86
149:	86
249:	86
506:	86
177:	85
71:	84
73:	84
79:	84
75:	84
305:	84
389:	84
205:	83
417:	83
361:	81
207:	80
179:	79
452:	79
480:	78
123:	76
251:	76
279:	76
335:	76
363:	76
151:	75
391:	75
419:	75
508:	75
307:	74
6:	65
63:	55
276:	55
159:	54
39:	53
55:	53
43:	52
51:	52
59:	52
62:	52
383:	52
47:	51
329:	51
106:	49
215:	46
482:	36
427:	30
426:	27
481:	27
16:	26
346:	23
68:	22
74:	21
326:	21
404:	21
52:	20
280:	20
14:	19
64:	19
124:	19
235:	19
240:	19
342:	19
32:	18
66:	18
98:	18
100:	18
298:	18
318:	18
504:	18
2:	17
4:	17
72:	17
132:	17
176:	17
234:	17
247:	17
264:	17
284:	17
352:	17
378:	17
380:	17
429:	17
461:	17
477:	17
507:	17
509:	17
515:	17
523:	17
34:	16
50:	16
82:	16
94:	16
110:	16
120:	16
140:	16
152:	16
169:	16
172:	16
182:	16
200:	16
212:	16
220:	16
228:	16
250:	16
310:	16
314:	16
334:	16
336:	16
362:	16
399:	16
475:	16
489:	16
525:	16
18:	15
40:	15
42:	15
44:	15
60:	15
108:	15
109:	15
114:	15
118:	15
128:	15
134:	15
162:	15
202:	15
222:	15
236:	15
256:	15
270:	15
288:	15
295:	15
306:	15
332:	15
358:	15
433:	15
437:	15
442:	15
503:	15
12:	14
76:	14
105:	14
112:	14
146:	14
148:	14
156:	14
158:	14
174:	14
180:	14
192:	14
214:	14
252:	14
258:	14
263:	14
265:	14
268:	14
282:	14
287:	14
302:	14
303:	14
304:	14
322:	14
340:	14
348:	14
356:	14
370:	14
392:	14
422:	14
448:	14
463:	14
469:	14
476:	14
479:	14
497:	14
517:	14
20:	13
56:	13
67:	13
80:	13
84:	13
153:	13
168:	13
210:	13
242:	13
243:	13
261:	13
325:	13
327:	13
338:	13
386:	13
405:	13
406:	13
423:	13
439:	13
441:	13
473:	13
486:	13
495:	13
502:	13
513:	13
24:	12
26:	12
54:	12
113:	12
144:	12
147:	12
170:	12
208:	12
217:	12
239:	12
255:	12
269:	12
278:	12
285:	12
290:	12
294:	12
324:	12
339:	12
343:	12
364:	12
367:	12
388:	12
393:	12
420:	12
445:	12
470:	12
451:	12
462:	12
468:	12
484:	12
485:	12
490:	12
499:	12
28:	11
36:	11
48:	11
90:	11
103:	11
126:	11
137:	11
150:	11
154:	11
155:	11
165:	11
171:	11
175:	11
184:	11
188:	11
196:	11
230:	11
267:	11
283:	11
297:	11
331:	11
344:	11
345:	11
351:	11
357:	11
360:	11
369:	11
375:	11
376:	11
381:	11
382:	11
415:	11
416:	11
418:	11
428:	11
436:	11
455:	11
456:	11
459:	11
464:	11
483:	11
488:	11
514:	11
529:	11
8:	10
30:	10
38:	10
70:	10
107:	10
115:	10
119:	10
141:	10
145:	10
161:	10
173:	10
178:	10
183:	10
189:	10
195:	10
199:	10
201:	10
203:	10
213:	10
245:	10
253:	10
257:	10
259:	10
274:	10
286:	10
291:	10
292:	10
293:	10
312:	10
321:	10
350:	10
355:	10
372:	10
385:	10
390:	10
396:	10
398:	10
407:	10
410:	10
413:	10
447:	10
458:	10
460:	10
466:	10
471:	10
472:	10
492:	10
493:	10
500:	10
511:	10
518:	10
10:	9
88:	9
101:	9
111:	9
122:	9
129:	9
131:	9
133:	9
143:	9
157:	9
163:	9
167:	9
181:	9
185:	9
194:	9
216:	9
232:	9
246:	9
248:	9
266:	9
271:	9
289:	9
311:	9
315:	9
317:	9
328:	9
347:	9
354:	9
365:	9
371:	9
395:	9
377:	9
379:	9
384:	9
424:	9
430:	9
431:	9
453:	9
465:	9
491:	9
494:	9
496:	9
498:	9
510:	9
516:	9
520:	9
521:	9
530:	9
22:	8
58:	8
92:	8
97:	8
104:	8
102:	8
99:	8
117:	8
135:	8
193:	8
197:	8
206:	8
209:	8
211:	8
237:	8
254:	8
260:	8
272:	8
273:	8
281:	8
299:	8
300:	8
301:	8
309:	8
319:	8
323:	8
341:	8
359:	8
373:	8
401:	8
402:	8
408:	8
409:	8
412:	8
414:	8
425:	8
432:	8
434:	8
438:	8
440:	8
443:	8
444:	8
457:	8
467:	8
487:	8
505:	8
522:	8
524:	8
526:	8
528:	8
531:	8
46:	7
78:	7
86:	7
96:	7
116:	7
130:	7
138:	7
139:	7
142:	7
160:	7
164:	7
166:	7
187:	7
190:	7
198:	7
204:	7
241:	7
244:	7
275:	7
296:	7
308:	7
316:	7
349:	7
353:	7
366:	7
368:	7
374:	7
387:	7
394:	7
400:	7
403:	7
411:	7
435:	7
446:	7
449:	7
454:	7
501:	7
512:	7
527:	7
125:	6
127:	6
136:	6
186:	6
191:	6
218:	6
226:	6
238:	6
313:	6
320:	6
330:	6
337:	6
397:	6
519:	6
224:	5
262:	5
474:	5
61:	3
53:	2
45:	1
49:	1
57:	1
65:	1
83:	1
85:	1
87:	1
89:	1
91:	1
93:	1
95:	1

## Summary
Print a summary of the identified sequences for checking correctness.

In [34]:
import pandas as pd
import numpy as np

df = df.sort_values('timestamp').reset_index(drop=True)

step_summary = (
    df.groupby('step_number', as_index=False)
      .agg(
          label        = ('label', 'first'),
          phase_name   = ('phase_name', 'first'),
          phase_number = ('phase_number', 'first'),
          num_flws     = ('timestamp', 'size'),
          start_time   = ('timestamp', 'min'),
          end_time     = ('timestamp', 'max')
      )
      .assign(duration=lambda g: g['end_time'] - g['start_time'])
)

step_summary['fps'] = (
    step_summary['num_flws'] /
    step_summary['duration'].dt.total_seconds().replace(0, np.nan)
)

label_summary = (
    step_summary.groupby('label', as_index=False)
               .agg(
                   avg_num_flws    = ('num_flws', 'mean'),
                   median_num_flws = ('num_flws', 'median'),
                   avg_duration    = ('duration', 'mean'),
                   median_duration = ('duration', 'median'),
                   total_steps = ('step_number', 'nunique'),
                   total_flws      = ('num_flws', 'sum'),
                   avg_fps         = ('fps', 'mean')
               )
)

In [35]:
label_summary

,label,avg_num_flws,median_num_flws,avg_duration,median_duration,total_steps,total_flws,avg_fps
0,brute_force_malformed,659.000000,659.0,0 days 00:14:49.435000,0 days 00:14:49.435000,1,659,0.740920
1,dollar_char,12.018072,10.0,0 days 00:00:52.558548,0 days 00:00:47.397000,166,1995,0.233225
2,mqtt_cat,1.500000,1.0,0 days 00:00:01.198666,0 days 00:00:00,6,9,1.467646
3,nmap_10_T5,21015.444444,21010.0,0 days 00:00:52.132777,0 days 00:00:51.614000,9,189139,403.857130
4,nmap_banner,76.428571,76.0,0 days 00:01:00.220071,0 days 00:01:00.698500,14,1070,1.270563
5,nmap_mqtt,85.571429,86.0,0 days 00:03:57.972571,0 days 00:03:57.646000,21,1797,0.359606
6,nmap_sub,52.571429,52.0,0 days 00:00:52.265000,0 days 00:00:52.042000,7,368,1.006442
7,pause,13.003546,12.0,0 days 00:01:02.146588,0 days 00:01:02.526500,282,3667,0.212957
8,scp_inst,1.000000,1.0,0 days 00:00:00,0 days 00:00:00,7,7,NaN

In [36]:
step_summary

,step_number,label,phase_name,phase_number,num_flws,start_time,end_time,duration,fps
0,2,pause,PAUSE,-1,17,2025-08-19 19:11:17.475039+00:00,2025-08-19 19:12:18.459039+00:00,0 days 00:01:00.984000,0.278762
1,4,pause,PAUSE,-1,17,2025-08-19 19:12:24.506039+00:00,2025-08-19 19:13:54.169039+00:00,0 days 00:01:29.663000,0.189599
2,5,nmap_10_T5,RECONNAISSANCE,1,21017,2025-08-19 19:14:01.213039+00:00,2025-08-19 19:14:52.827039+00:00,0 days 00:00:51.614000,407.195722
3,6,pause,PAUSE,-1,65,2025-08-19 19:14:54.563039+00:00,2025-08-19 19:16:07.065039+00:00,0 days 00:01:12.502000,0.896527
4,8,pause,PAUSE,-1,10,2025-08-19 19:16:13.117039+00:00,2025-08-19 19:16:57.445039+00:00,0 days 00:00:44.328000,0.225591
...,...,...,...,...,...,...,...,...,...
508,527,pause,PAUSE,-1,7,2025-08-20 05:03:02.231039+00:00,2025-08-20 05:03:32.219039+00:00,0 days 00:00:29.988000,0.233427
509,528,dollar_char,EXPLOIT,5,8,2025-08-20 05:03:32.470039+00:00,2025-08-20 05:04:16.718039+00:00,0 days 00:00:44.248000,0.180799
510,529,pause,PAUSE,-1,11,2025-08-20 05:04:24.760039+00:00,2025-08-20 05:05:21.969039+00:00,0 days 00:00:57.209000,0.192277
511,530,dollar_char,EXPLOIT,5,9,2025-08-20 05:05:22.210039+00:00,2025-08-20 05:06:08.451039+00:00,0 days 00:00:46.241000,0.194632
512,531,pause,PAUSE,-1,8,2025-08-20 05:06:12.477039+00:00,2025-08-20 05:06:54.758039+00:00,0 days 00:00:42.281000,0.189210

## Remove Pauses

In [37]:
df = df[df['label'] != 'pause']
df = df[df['label'] != 'discard']

In [38]:
df.shape

(195044, 93)

## Save labeled df to CSV

In [39]:
df.to_csv(root + 'dollar_char_train_labeled.csv', index=False)